server:
  port: 8081

spring:
  kafka:
    #bootstrap-servers: 192.168.1.100:9092,192.168.1.101:9093,192.168.1.102:9092
    #producer:
    #  retries: 3
    #  batch-size: 16384
    #  buffer-memory: 33554432
    #  key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #  value‐serializer: org.apache.kafka.common.serialization.StringSerializer
    #  acks: all
    consumer:
      #group-id: wyett-tmp-mygroup5
      #enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
