server:
  port: 8080

spring:
  kafka:
    #bootstrap-servers: 10.19.58.19:9093,10.19.58.19:9094,10.19.58.19:9095
    bootstrap-servers: 10.10.19.69:9092,10.10.19.69:9093,10.10.18.240:9092
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value‐serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: sns_canal_test_cluster_1_consumer
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer