server:
  port: 8080

spring:
  kafka:
    #bootstrap-servers: 10.19.58.19:9093,10.19.58.19:9094,10.19.58.19:9095
    bootstrap-servers: 10.16.17.103:9092,10.16.17.103:9093,10.16.17.107:9092
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value‐serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      group-id: I_vc_videocrawler_textcanalround2_2012111208_consumer
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer