server:
  port: 8080
  servlet:
    context-path: /scope
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8081
---
spring:
  profiles: prod
server:
  port: 8082
---
spring:
  profiles: prod
server:
  port: 8083