server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  data:
    mongodb:
      uri: mongodb://wyett_rw:jumpjump@192.168.0.1:27017,192.168.0.2:27017,192.168.0.3:27017/wyett?readPreference=secondaryPreferred
    # not support for mongodb 3.x
      #host: 192.168.0.1:27017,192.168.0.2:27017,192.168.0.3:27017
      #username: wyett_rw
      #password: jumpjump
      #database: wyett