server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  data:
    mongodb:
      uri: mongodb://username:xxxxxxxxxxx@xxxxxxxxxxx:10000,xxxxxxxxx:10000/dbname?readPreference=secondaryPreferred
      #&connectTimeoutMS=60000&ssl=false&serverSelectionTimeoutMS=5000
    # not support for mongodb 3.x
      #host: 192.168.0.1:27017,192.168.0.2:27017,192.168.0.3:27017
      #username: wyett_rw
      #password: jumpjump
      #database: wyett
      #database: timeline
      #authentication-database: timeline

