server:
  port: 8080
  servlet:
    context-path: /demo

http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 6000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

http_url:
  basic_str: localhost
  port: 8089


