server:
  port: 8080

spring:
  redis:
    database: 0
    password: 123456789
    timeout: 5000
    sentinel:
      master: mymaster
      #nodes: xxxxx:26379, ip2:26379, ip3:26379
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 3000
