server:
  port: 8080
  servlet:
    context-path: /binlogConsumer


rocketmq:
  name-server: 192.168.1.100:9876;192.168.1.101:9876;192.168.1.102:9876
#name-server: 127.0.0.1:9876

#myfilter:
#  operateType: INSERT
#  database: data
#  tables: instance_info
#  consumerGroup: rediscluster-consumer-group
