server:
  port: 8080
  servlet:
    context-path: /binlogConsumer


rocketmq:
  name-server: 127.0.0.1:9876

myfilter:
  operateType: INSERT
  database: data
  tables: instance_info
  consumerGroup: rediscluster-consumer-group
