server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://10.2.212.33:3306/member?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: member_rw
    password: jumpjump
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 10.2.212.33 # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  session:
    # spring session store
    store-type: redis
  security:
    user:
      name: wyett
      password: 123456
#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml
# 自定义redis键值
redis:
  key:
    prefix:
      token: "member:token:" #动态校验码前缀
    expire:
      token: 60 #动态校验码过期时间

#登录拦截验证
#member:
#  auth:
#    shouldSkipUrls:
#      - /sso/**
#      - /home/*